[package]
name = 'satay'
version = '1.0.0'

[addresses]
satay = "e3eaddfcc4d7436d26fef92ee39685ef176e3513dc736d116129ce055c07afac"

[dependencies.Liquidswap]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'v0.4.3'

[dependencies.satay-ditto-farming]
local = './structured_products/ditto_farming'