[package]
name = 'satay'
version = '1.0.0'

[addresses]
satay = "0x44"

# latest 'main' with any.move
[dependencies.Liquidswap]
git = 'git@github.com:pontem-network/liquidswap.git'
rev = '843b78ae538883a3ae6bacc16f93c3da79844ec2'

[dependencies.LiquidswapLP]
git = "https://github.com/pontem-network/liquidswap-lp.git"
rev = "72bc9ce31dd24659f1d35c6f0a0ffdb0b2d7b139"
