[package]
name = 'satay'
version = '1.0.0'

[addresses]
satay = "0x42"
usdc_vault = "0x43"

# latest 'main' with any.move
[dependencies.Liquidswap]
git = 'git@github.com:pontem-network/liquidswap.git'
rev = 'v0.2.6'

[dependencies.LiquidswapLP]
git = "git@github.com:pontem-network/liquidswap-lp.git"
rev = "v0.4.7"
