[package]
name = 'SatayCoins'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
satay_coins = "0x869ec26e021e97bef32f7e4fc33fc8afdd6a617d1c1255a5ab99ff4056b3cd5c"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "d57b97bae0b64b617869f2ff26e749e503848846"
subdir = "aptos-move/framework/move-stdlib"