[package]
name = 'satay-ditto-rewards'
version = '1.0.0'

[addresses]
satay_ditto_rewards = "c09622c20bdd49b2b83b7e05c264a62cfedeb45eaf5c629d0f0174917d801aef"

[dependencies.Liquidswap]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'v0.4.0'

[dependencies.ditto-interface]
git = "https://github.com/ditto-research/ditto-interface.git"
rev = "master"