[package]
name = 'satay-tortuga-farming'
version = '1.0.0'

[addresses]
satay_tortuga_farming = "0x895cff28180ccdd3746a22a5e8ff929060d4ae58510a97662d90339100ed75c7"

[dependencies.tortuga-staking]
local = '../../interfaces/tortuga-staking-interface'

[dependencies.aries-interface]
local = '../../interfaces/aries-interface'

[dependencies.aux-interface]
local='../../interfaces/aux-interface'