[package]
name = 'SatayInit'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
satay = "0xe9e742086a94cac35d2a09fc742726170cf3d4d97feda6c7d5e49d0cc06b3a30"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "d57b97bae0b64b617869f2ff26e749e503848846"
subdir = "aptos-move/framework/aptos-framework"
