[package]
name = 'satay-ditto-farming'
version = '1.0.0'

[addresses]
satay_ditto_farming = "0xb2104bc99e57db595ad246a46ff3d57adce17fb33058703ae770c302d0a88b63"

[dependencies.LiquidswapRouterV2]
git = 'https://github.com/pontem-network/liquidswap'
rev = 'v0.4.3'
subdir = './liquidswap_router_v2'

[dependencies.ditto-staking]
local = '../../interfaces/ditto-staking-interface'