name: Satay Package Tests
on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - v*

jobs:
  tests:
    name: Test Satay Package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Aptos
        uses: pontem-network/get-aptos@main
        with:
          version: aptos-cli-v0.3.9

      - name: Build
        run: aptos move compile

      - name: Test
        run: aptos move test
